"""Environment-bound configuration objects.

This module provides Pydantic BaseSettings-based configuration loading from .env files.
All settings classes automatically load from environment variables with support for
multiple alias names (e.g., MODEL_BASIC_* and MODEL_BASE_* both work).

Example:
    from generalAgent.config.settings import get_settings

    settings = get_settings()  # Cached singleton
    api_key = settings.models.reason_api_key
    max_loops = settings.governance.max_loops
"""

from __future__ import annotations

from functools import lru_cache
from typing import Optional

from dotenv import load_dotenv
from pydantic import AliasChoices, BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


load_dotenv()


class ModelRoutingSettings(BaseSettings):
    """Vendor-neutral model identifiers and credentials.

    Automatically loads from .env file with support for multiple alias names:
    - MODEL_BASE, MODEL_BASE_ID, MODEL_BASIC_ID (DeepSeek/generic base model)
    - MODEL_REASON, MODEL_REASON_ID, MODEL_REASONING_ID (reasoning model)
    - MODEL_VISION, MODEL_VISION_ID, MODEL_MULTIMODAL_ID (vision model)
    - MODEL_CODE, MODEL_CODE_ID (code generation model)
    - MODEL_CHAT, MODEL_CHAT_ID (chat model)

    Each model slot has three fields: id, api_key, base_url.
    """

    base: str = Field(
        default="base-quick",
        validation_alias=AliasChoices("MODEL_BASE", "MODEL_BASE_ID", "MODEL_BASIC_ID"),
    )
    base_api_key: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_BASE_API_KEY", "MODEL_BASIC_API_KEY"),
    )
    base_base_url: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_BASE_URL", "MODEL_BASIC_BASE_URL"),
    )
    base_context_window: int = Field(
        default=128000,
        validation_alias=AliasChoices("MODEL_BASE_CONTEXT_WINDOW", "MODEL_BASIC_CONTEXT_WINDOW"),
    )
    base_max_completion_tokens: int = Field(
        default=2048,
        ge=512,
        le=204800,
        validation_alias=AliasChoices(
            "MODEL_BASE_MAX_COMPLETION_TOKENS",
            "MODEL_BASIC_MAX_COMPLETION_TOKENS",
            "MODEL_BASE_MAX_TOKENS",  # Backward compatibility
            "MODEL_BASIC_MAX_TOKENS",  # Backward compatibility
        ),
        description="Maximum output tokens for base model (completion tokens generated by model)",
    )

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    reason: str = Field(
        default="reasoner-pro",
        validation_alias=AliasChoices("MODEL_REASON", "MODEL_REASON_ID", "MODEL_REASONING_ID"),
    )
    reason_api_key: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_REASON_API_KEY", "MODEL_REASONING_API_KEY"),
    )
    reason_base_url: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_REASON_URL", "MODEL_REASONING_BASE_URL"),
    )
    reason_context_window: int = Field(
        default=128000,
        validation_alias=AliasChoices("MODEL_REASON_CONTEXT_WINDOW", "MODEL_REASONING_CONTEXT_WINDOW"),
    )
    reason_max_completion_tokens: int = Field(
        default=2048,
        ge=512,
        le=204800,
        validation_alias=AliasChoices(
            "MODEL_REASON_MAX_COMPLETION_TOKENS",
            "MODEL_REASONING_MAX_COMPLETION_TOKENS",
            "MODEL_REASON_MAX_TOKENS",  # Backward compatibility
            "MODEL_REASONING_MAX_TOKENS",  # Backward compatibility
        ),
        description="Maximum output tokens for reasoning model (includes reasoning tokens)",
    )

    vision: str = Field(
        default="vision-omni",
        validation_alias=AliasChoices("MODEL_VISION", "MODEL_VISION_ID", "MODEL_MULTIMODAL_ID"),
    )
    vision_api_key: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_VISION_API_KEY", "MODEL_MULTIMODAL_API_KEY"),
    )
    vision_base_url: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_VISION_URL", "MODEL_MULTIMODAL_BASE_URL"),
    )
    vision_context_window: int = Field(
        default=64000,
        validation_alias=AliasChoices("MODEL_VISION_CONTEXT_WINDOW", "MODEL_MULTIMODAL_CONTEXT_WINDOW"),
    )
    vision_max_completion_tokens: int = Field(
        default=2048,
        ge=512,
        le=204800,
        validation_alias=AliasChoices(
            "MODEL_VISION_MAX_COMPLETION_TOKENS",
            "MODEL_MULTIMODAL_MAX_COMPLETION_TOKENS",
            "MODEL_VISION_MAX_TOKENS",  # Backward compatibility
            "MODEL_MULTIMODAL_MAX_TOKENS",  # Backward compatibility
        ),
        description="Maximum output tokens for vision model",
    )

    code: str = Field(
        default="code-pro",
        validation_alias=AliasChoices("MODEL_CODE", "MODEL_CODE_ID"),
    )
    code_api_key: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_CODE_API_KEY", "MODEL_CODEKIT_API_KEY"),
    )
    code_base_url: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_CODE_URL", "MODEL_CODE_BASE_URL"),
    )
    code_context_window: int = Field(
        default=200000,
        validation_alias=AliasChoices("MODEL_CODE_CONTEXT_WINDOW"),
    )
    code_max_completion_tokens: int = Field(
        default=2048,
        ge=512,
        le=204800,
        validation_alias=AliasChoices(
            "MODEL_CODE_MAX_COMPLETION_TOKENS",
            "MODEL_CODE_MAX_TOKENS",  # Backward compatibility
        ),
        description="Maximum output tokens for code model (code generation)",
    )

    chat: str = Field(
        default="chat-mid",
        validation_alias=AliasChoices("MODEL_CHAT", "MODEL_CHAT_ID"),
    )
    chat_api_key: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_CHAT_API_KEY", "MODEL_DEFAULT_CHAT_API_KEY"),
    )
    chat_base_url: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("MODEL_CHAT_URL", "MODEL_CHAT_BASE_URL"),
    )
    chat_context_window: int = Field(
        default=256000,
        validation_alias=AliasChoices("MODEL_CHAT_CONTEXT_WINDOW"),
    )
    chat_max_completion_tokens: int = Field(
        default=2048,
        ge=512,
        le=204800,
        validation_alias=AliasChoices(
            "MODEL_CHAT_MAX_COMPLETION_TOKENS",
            "MODEL_CHAT_MAX_TOKENS",  # Backward compatibility
        ),
        description="Maximum output tokens for chat model (tool calls, conversation)",
    )


class GovernanceSettings(BaseSettings):
    """Runtime governance and control settings.

    Controls agent behavior limits and policies:
    - auto_approve_writes: Skip HITL approval for file writes (default: False)
    - max_loops: Maximum agent loop iterations (1-500, default: 100)
    - max_message_history: Message history window size (10-100, default: 40)
    """

    auto_approve_writes: bool = Field(default=False, alias="AUTO_APPROVE_WRITES")
    max_loops: int = Field(default=100, ge=1, le=500)
    max_message_history: int = Field(default=40, ge=10, le=100, alias="MAX_MESSAGE_HISTORY")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class ObservabilitySettings(BaseSettings):
    """Tracing, logging, and persistence configuration.

    Controls observability features:
    - LangSmith tracing (LANGCHAIN_TRACING_V2, LANGCHAIN_PROJECT, etc.)
    - Logging settings (LOG_PROMPT_MAX_LENGTH)
    - Session persistence (SESSION_DB_PATH for SQLite storage)
    """

    langsmith_project: Optional[str] = Field(default=None, alias="LANGCHAIN_PROJECT")
    langsmith_api_key: Optional[str] = Field(
        default=None, validation_alias=AliasChoices("LANGCHAIN_API_KEY", "LANGSMITH_API_KEY")
    )
    langsmith_endpoint: Optional[str] = Field(default=None, alias="LANGCHAIN_ENDPOINT")
    tracing_enabled: bool = Field(default=False, alias="LANGCHAIN_TRACING_V2")

    # Logging settings
    log_prompt_max_length: int = Field(default=500, ge=100, le=5000, alias="LOG_PROMPT_MAX_LENGTH")

    # Session persistence database path
    # Default: ./data/sessions.db (SQLite)
    # Set to empty string to disable persistence
    session_db_path: Optional[str] = Field(default=None, alias="SESSION_DB_PATH")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class ContextManagementSettings(BaseSettings):
    """上下文管理配置

    控制上下文压缩和 Token 管理功能：
    - enabled: 是否启用上下文管理
    - info_threshold: 信息提示阈值（75%）
    - warning_threshold: 警告阈值（85%）
    - critical_threshold: 强制压缩阈值（95%）
    - keep_recent_messages: 保留最近消息数
    - compact_middle_messages: 压缩中间消息数
    - compression_ratio_threshold: 压缩率阈值（决定策略切换）
    - compact_cycle_limit: 连续 compact 次数限制
    - max_history_messages: 硬上限（后备策略）
    """

    enabled: bool = Field(default=True, alias="CONTEXT_MANAGEMENT_ENABLED")

    # Token 监控阈值
    # ge 下限 le 上限
    info_threshold: float = Field(default=0.75, ge=0.5, le=0.95, alias="CONTEXT_INFO_THRESHOLD")
    warning_threshold: float = Field(default=0.85, ge=0.6, le=0.95, alias="CONTEXT_WARNING_THRESHOLD")
    critical_threshold: float = Field(default=0.95, ge=0.8, le=0.99, alias="CONTEXT_CRITICAL_THRESHOLD")

    # 分层策略配置
    keep_recent_messages: int = Field(default=10, ge=5, le=50, alias="CONTEXT_KEEP_RECENT")
    compact_middle_messages: int = Field(default=30, ge=10, le=100, alias="CONTEXT_COMPACT_MIDDLE")

    # 动态策略决策配置
    compression_ratio_threshold: float = Field(default=0.4, ge=0.2, le=0.8, alias="CONTEXT_COMPRESSION_RATIO_THRESHOLD")
    compact_cycle_limit: int = Field(default=3, ge=1, le=10, alias="CONTEXT_COMPACT_CYCLE_LIMIT")

    # Kimi-inspired 后备策略
    max_history_messages: int = Field(default=100, ge=30, le=200, alias="CONTEXT_MAX_HISTORY")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class DocumentSettings(BaseModel):
    """Document extraction and search configuration.

    These settings control how documents (PDF/DOCX/XLSX/PPTX) are read,
    extracted, and indexed for search.
    """

    # Text file limits
    text_file_max_size: int = 10_000  # 10KB - full read threshold
    text_preview_chars: int = 5_000   # 5K chars - preview size for large text files

    # PDF preview limits
    pdf_preview_pages: int = 5
    pdf_preview_chars: int = 5_000

    # DOCX preview limits
    docx_preview_pages: int = 5
    docx_preview_chars: int = 5_000

    # XLSX preview limits
    xlsx_preview_sheets: int = 3
    xlsx_preview_chars: int = 5_000

    # PPTX preview limits
    pptx_preview_slides: int = 10
    pptx_preview_chars: int = 5_000

    # Chunking settings (业界最佳实践: 100-300 tokens for keyword search)
    chunk_max_size: int = 400          # Max characters per chunk (约 100-130 tokens 中文)
    chunk_overlap: int = 80             # Overlap between chunks (20%)
    chunk_min_size: int = 50            # Min chunk size to avoid over-fragmentation

    # XLSX specific chunking
    xlsx_rows_per_chunk: int = 20       # Number of rows per chunk for large sheets

    # Tokenization settings (中文优化)
    use_jieba: bool = True              # Use jieba for Chinese word segmentation
    remove_stopwords: bool = True        # Remove common stopwords

    # N-gram settings
    use_bigrams: bool = True            # Extract bigrams for better matching
    use_trigrams: bool = True           # Extract trigrams for phrase matching

    # Search algorithm settings
    search_algorithm: str = "bm25"      # "bm25" (standard) or "simple" (multi-strategy)
    bm25_k1: float = 1.2                # BM25 term frequency saturation parameter
    bm25_b: float = 0.75                # BM25 document length normalization

    # Index backend (2025-10-27: 已全面切换至 FTS5)
    # - 大小写不敏感
    # - 英文词干提取（baseline = baselines）
    # - 中文 jieba 分词支持
    # - SQLite FTS5 高性能倒排索引
    index_backend: str = "fts5"  # Fixed: FTS5 only

    # Search settings
    search_max_results_default: int = 5

    # Index settings
    index_stale_threshold_hours: int = 24  # Rebuild index if file modified within 24h


class Settings(BaseSettings):
    """Root application settings loaded from .env file.

    Hierarchical structure containing five nested settings groups:
    - models: Model routing and API credentials (ModelRoutingSettings)
    - governance: Agent behavior controls (GovernanceSettings)
    - observability: Tracing and logging (ObservabilitySettings)
    - context: Context management and compression (ContextManagementSettings)
    - documents: Document processing settings (DocumentSettings)

    All values are automatically loaded from .env via Pydantic BaseSettings.
    Use get_settings() to obtain a cached singleton instance.
    """

    environment: str = Field(default="dev", alias="APP_ENV")
    models: ModelRoutingSettings = Field(default_factory=ModelRoutingSettings)
    governance: GovernanceSettings = Field(default_factory=GovernanceSettings)
    observability: ObservabilitySettings = Field(default_factory=ObservabilitySettings)
    context: ContextManagementSettings = Field(default_factory=ContextManagementSettings)
    documents: DocumentSettings = Field(default_factory=DocumentSettings)

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        validate_assignment=True,
        case_sensitive=False,
    )


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return a cached singleton Settings instance.

    Uses LRU cache to ensure only one Settings object is created per process.
    All configuration is automatically loaded from .env file.

    Returns:
        Settings: Cached application settings instance
    """
    return Settings()
